stages:
  preprocess:
    cmd: python data_preprocess.py --input-dir data/raw/shmuhammad_AfriSenti-twitter-sentiment/
      --output-dir preprocessed_data/
    deps:
    - data/raw/shmuhammad_AfriSenti-twitter-sentiment/ibo_test.csv
    - data/raw/shmuhammad_AfriSenti-twitter-sentiment/ibo_train.csv
    - data/raw/shmuhammad_AfriSenti-twitter-sentiment/ibo_validation.csv
    - data_preprocess.py
    outs:
    - preprocessed_data/test.csv
    - preprocessed_data/train.csv
    - preprocessed_data/val.csv
  hyperparameter_search:
    cmd: python hyperparameter_search.py
    deps:
    - evaluation.py
    - checkpoint-1520000/
    - hyperparameter_search.py
    - preprocessed_data/train.csv
    - preprocessed_data/val.csv
    outs:
    - best_hyperparameters.json
  train:
    cmd: python train.py
    deps:
    - best_hyperparameters.json
    - evaluation.py
    - checkpoint-1520000/
    - preprocessed_data/test.csv
    - preprocessed_data/train.csv
    - preprocessed_data/val.csv
    - train.py
    outs:
    - models/fine_tuned_igbo_sentiment/
    - results/checkpoint-1274/
    - results/metrics.txt
  evaluation:
    cmd: python evaluation.py
    deps: 
    - models/fine_tuned_igbo_sentiment/
    - preprocessed_data/test.csv
    outs:
    - evaluation_results.json

