name: CML CI/CD Pipeline

permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main

jobs:
  train-and-report:
    runs-on: ubuntu-latest 
    timeout-minutes: 50400 # 35 days
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        run: |
          dvc pull data
          pip install -r requirements.txt
          dvc repro
      - name: Create CML report
        run: |
          # Model Performance Report
          ## Training metrics
          $(dvc params diff main --show-md)
          ## Print metrics of the current branch
          dvc metrics show --md >> report.md
          # Compare metrics with the main branch
          git fetch --prune
          dvc metrics diff --md main >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: train-and-report
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t tonysoro/ibo-sentiment-app:latest .
      - name: Push Docker image to Docker Hub
        run: docker push tonysoro/ibo-sentiment-app:latest
      - name: Deploy to AWS ECS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1"
        run: |
          aws ecs update-service --cluster my-cluster --service my-service --force-new-deployment